FROM microsoft/dotnet:2-sdk
COPY . /app
WORKDIR /app/test/Expected.Request.Tests
RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /app/wait_for_it.sh \
    && dotnet restore && dotnet build -f netcoreapp2