FROM microsoft/dotnet:2-sdk
COPY . /app
WORKDIR /app/test/Expected.Request.Tests
RUN apt-get update && apt-get install dotnet-sdk-1.0.4
RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /app/wait_for_it.sh \
    && dotnet restore